
stages:
  - containers
  - builds
  - sanity_checks
  - publish

.native_build_job:
  extends: .gitlab_native_build_job
  before_script:
    - export MAKEFLAGS="-j$(getconf _NPROCESSORS_ONLN)"
  script:
    - git clone --depth 1 https://gitlab.com/libvirt/libvirt-publican.git brand
    - $MAKE branddir=$PWD/brand

include: '/ci/gitlab.yml'

# Would be called 'ubuntu-2004-docs', but it needs the
# special 'docs' name, as it is the one we publish from
pages:
  image: $CI_REGISTRY_IMAGE/ci-ubuntu-2004:latest
  stage: publish
  needs:
    - x86_64-ubuntu-2004
  script:
    - mv tmp/en-US/html public
  artifacts:
    paths:
      - public
