
stages:
  - containers
  - builds
  - sanity_checks
  - publish

.native_build_job:
  script:
    - export MAKEFLAGS="-j$(getconf _NPROCESSORS_ONLN)"
    - git clone --depth 1 https://gitlab.com/libvirt/libvirt-publican.git brand
    - $MAKE branddir=$PWD/brand

.native_build_job_prebuilt_env:
  extends:
    - .native_build_job
    - .gitlab_native_build_job_prebuilt_env

.native_build_job_local_env:
  extends:
    - .native_build_job
    - .gitlab_native_build_job_local_env

include: '/ci/gitlab.yml'

# Would be called 'ubuntu-2004-docs', but it needs the
# special 'docs' name, as it is the one we publish from
pages:
  image: $CI_REGISTRY_IMAGE/ci-ubuntu-2004:latest
  stage: publish
  needs:
    - x86_64-ubuntu-2004-prebuilt-env
  script:
    - mv tmp/en-US/html public
  rules:
    - if: '$CI_PROJECT_NAMESPACE == $RUN_UPSTREAM_NAMESPACE && $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
      when: on_success
  artifacts:
    paths:
      - public
